<div class="block block-dashboard-additionalinfo">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Additional Information')) ?></strong></div>
    <div class="block-content">
        <strong class="box-title">
            <span><?= $block->escapeHtml(__('Parent\'s Information')) ?></span>
        </strong>
        <div class="box-content">
            <p>Father's Name : </p>
            <p>Mother's Name : </p>
        </div>
    </div>
</div>
