<?php if($this->helper(\TrainingShubham\CustomerAttribute\Helper\Data::class)->isFatherNameEnable()) : ?>
    <div class="field father_name required">
        <label class="label" for="father_name">
            <span><?= $block->escapeHtml(__('Father\'s Name')) ?></span>
        </label>
        <div class="control">
            <input type="text" name="father_name" id="father_name" value="" title="<?= $block->escapeHtmlAttr(__('Father\'s Name')) ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
<?php endif; ?>

<?php if($this->helper(\TrainingShubham\CustomerAttribute\Helper\Data::class)->isMotherNameEnable()) : ?>
    <div class="field mother_name required">
        <label class="label" for="mother_name">
            <span><?= $block->escapeHtml(__('Mother\'s Name')) ?></span>
        </label>
        <div class="control">
            <input type="text" name="mother_name" id="mother_name" value="" title="<?= $block->escapeHtmlAttr(__('Mother\'s Name')) ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
<?php endif; ?>